### PR TITLE
Info displaying number of test failing and total test

### PR DESCRIPTION
**Pull request by sudazzle**
Info displaying number of test failing and total test at the end of the iteration and added a condition to throw an error to enable ci in gitlab or github to send an email to the stakeholders when any number of tests fails

### CODE REVIEW

**Comment by czardoz** [comment]
@sudazzle, We already have a count of failed and pass tests at the end of each iteration:

```Parent                   	Pass Count	 FailCount
-----------------------------------------------------------
Folder Auth: Digest      	         4	         0
Folder Auth: Others      	         4	         0
Folder Cookies           	        10	         1
Folder Headers           	         2	         1
Folder Request Methods   	        21	         3
Folder Utilities         	        11	         0
Folder [draft] Auth: O...	         7	         0

Total                    	        59	         5
```

**Comment by czardoz** [comment]
Also you can use the "--stopOnError" option to ensure that Newman exits with a non-zero error code, which should cause most CI systems to fail.

**Comment by sudazzle** [comment]
I am running the test with grunt and I want to display the total number failed tests and the total number of tests ran at the end of the iteration. I recently installed the newman@beta but it didn't display the message.

**Comment by czardoz** [comment]
Probably something to do with your setup? :)

Iteration summary is available on our travis builds as well: https://travis-ci.org/postmanlabs/newman/builds/106189117

**Comment by sudazzle** [comment]
And i don't want to hault the running test with stopOnError. I want to run the whole test and at the end of the iteration I want the CI build to fail

**Comment by czardoz** [comment]
You can use "-x" or "--exitCode" option for that. From the readme:

```-x, --exitCode              Continue running tests even after a failure, but exit with code=1```

**Comment by sudazzle** [comment]
Yeah may be my setup in grunt is not right. I am using grunt to run the newman. I will go back again to my code and see. Thank you guys. :)

**Comment by czardoz** [comment]
No problem, and thanks a lot for creating a pull request!

I'm closing this one, since it seems that newman already has these functionalities. :)

**Comment by sudazzle** [comment]
No problem :)

**Comment by sudazzle** [comment]
is this is latest release 2.0.0-beta.4

**Pull request closed without merging**
