### PR TITLE
Fix for #687 - add tests attribute to the junit reporter this

### PR DESCRIPTION
**Pull request by mcdan**
output correctly conforms to the XSD.

### CODE REVIEW

**Comment by mcdan** [comment]
I didn't build tests for this as there isn't a pattern for validating the output for the reporters that I could find in the test harness and I was hesitant to try and define it without further guidance.

**Comment by shamasis** [comment]
@czardoz can you guide this to completion? And also possibly look as whether we can run all sanity tests with JUnit reporter and see how we can alleviate the XSD here http://llg.cubic.org/docs/junit/

@mcdan thank you 😍

**Comment by czardoz** [comment]
Thanks @mcdan !

**Comment by mcdan** [comment]
No problem. Ping me if you want help with the tests / a guinea pig for a
release.

**Pull request merged**
