### PR TITLE
feat: Multiple file support

### LINKED ISSUE #2215: passing multiple csv files to a collection runner in newman
How to pass multiple csv files in newman run?

newman run CollectionRunner.json --global-var IP_PORT="http://127.0.0.1:8088/" -r htmlextra --reporter-htmlextra-title "Result Report" --reporter-htmlextra-export /home/reports/HARISH.html --iteration-data /home/dataset1.csv

I want to pass multiple data sets to the collection, I have dataset1,dataset2,dataset3,dataset4 in my directory. all should gets executed for the collectionRunner and the RESULT REPORT should contain all the result,

I tried something like this, newman run CollectionRunner.json --global-var IP_PORT="http://127.0.0.1:8088/" -r htmlextra --reporter-htmlextra-title "Result Report" --reporter-htmlextra-export /home/reports/Result.html --iteration-data /home/dataset1.csv --iteration-data /home/dataset2.csv --iteration-data /home/dataset3.csv

But its not working

### PR DESCRIPTION
**Pull request by adrijshikhar**
fix #2215  

Add multiple file support with `--iteration-data` flag. Right now it checks whether the location is array or not. If its an array then check whether it has an object inside it or not. If it has no object, then it is an array of location and data is parsed for each location and then passed on, and if not an array, location variable is treated as string.

PS: this is initial implementation of the feature. i will refactor it according to the existing code.

### CODE REVIEW

**Comment by adrijshikhar** [comment]
travis build is failing probably because now location is being passed as an array of strings and checks are written for string location. I will fix this too across the repo.

**Comment by adrijshikhar** [comment]
my exams are going on. they will be over on 9th March. i will finish this as soon as they get over.

**Comment by prabalsingh24** [comment]
Hi I am also a student, I saw the changes you made. I might be wrong but I don't think you had to commit changes in package-lock.json and package.json.

**Comment by adrijshikhar** [comment]
I did not commit them, thats the bot.

**Comment by prabalsingh24** [comment]
Yeah sorry :( XD

**Pull request closed without merging**
