### PR TITLE
Resilient csv parsing

### PR DESCRIPTION
**Pull request by kunagpal**

### CODE REVIEW

**Comment by czardoz** [comment]
What was the original behaviour?

**Comment by kunagpal** [comment]
@shamasis @czardoz The default escape character is `"`, which is has now been changed to `\`.

**Comment by shamasis** [comment]
Seems in the right direction. But this could be breaking change for many. And as such, should be a minor upgrade candidate with enough caveat. 

Any way we can test the impact on a greater subset?

**Comment by shamasis** [comment]
However if the app already behaves like this, we can go ahead and merge.

**Comment by kunagpal** [comment]
@shamasis As @madebysid has pointed out, the app does behave like this.

**Pull request merged**
