### PR TITLE
Adjustable terminal width

### PR DESCRIPTION
**Pull request by kunagpal**
This takes care of #1203

### CODE REVIEW

**Comment by kunagpal** [comment]
Needs to be reworked for `commander`.

**Comment by connorsadlervelo** [comment]
Is this not supported in the newer versions of newman?
I am seeing wide console logging from the command line in Mac OS but it's limited to 80 chars when run in Jenkins

**Comment by kunagpal** [comment]
@connorsadlervelo This was to allow tweaking the width restriction applied to console output within collection scripts. Regular CLI reporter output will try to intelligently detect the current width, as can be seen here: https://github.com/postmanlabs/newman/blob/develop/lib/reporters/cli/cli-utils.js#L133

**Comment by connorsadlervelo** [comment]
Thanks for that - should that intelligent logic work on Jenkins? It seems to limit the width there

**Comment by shamasis** [comment]
@kunagpal also when we rework on this, the option should be CLI reporter specific

**Pull request closed without merging**
