### PR TITLE
Fix undefined cols width for failures summary

### PR DESCRIPTION
**Pull request by unmultimedio**
Related to https://github.com/postmanlabs/newman/issues/885

### CODE REVIEW

**Comment by unmultimedio** [comment]
Tested with my fork, it works now:

dev-us1_1MTcz_TESTRUNNER_JOB__16_Console__Jenkins_

**Comment by shamasis** [comment]
Thanks for the PR. Will get this checked and merged asap.

**Comment by unmultimedio** [comment]
Hi @shamasis, any news on this?

**Review by codenirvana — APPROVED** [review]
LGTM 👍

**Pull request merged**
