### PR TITLE
Removed iterationData inheritance from iterationCount

### PR DESCRIPTION
**Pull request by kunagpal**

### CODE REVIEW

**Comment by czardoz** [comment]
@kunagpal How was this tested?

**Comment by shamasis** [comment]
Looks good to me. Not sure if there were previous unit / integration tests watching out for this. Maybe a test should be there that send data file with X rows and it is tested that iteration runs for X rows. The other test is where data contains X rows but iterationCount is set to Y and test is done to check iteration runs for Y count.

**Comment by czardoz** [comment]
@shamasis There were no tests watching for this, because we do not have a way (yet) to ensure that "n" iterations were run for CLI usage. 

@kunagpal How was this tested?

**Comment by kunagpal** [comment]
@czardoz @shamasis: Testing manually for now, see #616

**Pull request merged**
