### PR TITLE
Added publish scripts for docs and wiki

### PR DESCRIPTION
**Pull request by kunagpal**

### CODE REVIEW

**Comment by czardoz** [comment]
:+1: @shamasis

**Comment by czardoz** [comment]
@kunagpal Can you add the scripts to `package.json`, we'll be able to get this PR merged then. :)

**Comment by kunagpal** [comment]
@czardoz Done.

**Comment by czardoz** [comment]
Oops, integration tests are failing. I think you need to merge develop into this.

**Comment by kunagpal** [comment]
@czardoz Merged.

**Pull request merged**
