### PR TITLE
Add --iteration-data-range option

### PR DESCRIPTION
**Pull request by preyunk**
This option enables dynamic iteration of data file
this option will accept start index and an optional end index to
select a range from start to end - 1.

Fixes: https://github.com/postmanlabs/newman/issues/2560

### CODE REVIEW

**Comment by preyunk** [comment]
This will probably need some tests for invalid values of start and end index

**Comment by adityaofficial10** [comment]
@preyunk 
I guess you'll need some tests to ensure proper coverage.

**Comment by preyunk** [comment]
@shamasis @codenirvana 
Can you take a look if the approach to implementing the feature is correct?

**Review by codenirvana — CHANGES_REQUESTED** [review]
I feel there's a need for `from` and `to` instead of asking for the complete `range`.

Also, the count should be 1-based (instead of 0).

**Comment by Xdomen** [comment]
@preyunk can I somehow help with the outstanding comments? :)

**Comment by preyunk** [comment]
> @preyunk can I somehow help with the outstanding comments? :)

Yeah, sure 😀

**Comment by Xdomen** [comment]
@preyunk seems like I bit more than I could chew, I don't know how to make the necessary changes, so If you could take over I would be really grateful 🙏  Sincere aplogies for the inconvenience..

**Review by shamasis — CHANGES_REQUESTED** [review]
https://github.com/postmanlabs/newman/pull/2652

Control which range of iteration. There seems to be two more PRs with same agenda.

- https://github.com/postmanlabs/newman/pull/2652
- https://github.com/postmanlabs/newman/pull/2664/files
- https://github.com/postmanlabs/newman/pull/2896

All the above seems off. These should be done at runtime level. Instead of manipulating data file, runtime itself should start and end on specific iterations. It would also help it make portable across CLI and App

**Pull request closed without merging**
