### PR TITLE
Feature: Single Request Command initialised..

### LINKED ISSUE #2548: Add Feature to perform Individual Requests
1. Newman Version (can be found via `newman -v`): 5.2.0
 2. OS details (type, version, and architecture): Windows10 Pro, 64bit
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there:  Came to my mind recently, always there
 4. Expected behaviour: To perform individual Requests instead of just running Collections

We can have a set of commands to execute individual Get, Post, Put, etc. requests too and return the responses.
For example: 
- `newman -get "http://website.com/getpage" `
- `newman -post --bodyjson "{"id":"4"}" "http://website.com/postpage" `

### LINKED ISSUE #2566: [Feature Request] Enable running single request from the folder/collection
1. Newman Version (can be found via newman -v): 5.2.1
2. OS details (type, version, and architecture): Linux
3. Are you using Newman as a library, or via the CLI? CLI
4. Did you encounter this recently, or has this bug always been there: Always

Steps to reproduce the problem:
1. newman run collection.json -e dev_env.json --folder RequestFolder/PostRequest

Expected behaviour:
- should run the single request

### PR DESCRIPTION
**Pull request by adityaofficial10**
Fixes #2548 
I am still working on this PR.
Since this involves a lot of changes, I'd go step by step to ensure the repo remains clean.

### CODE REVIEW

**Comment by adityaofficial10** [comment]
@codenirvana @shamasis @vvs11
I have the idea and implementation ready for this GSoC project idea.
I've sent you an email regarding my thoughts on this.
If you could review them, we can discuss my proposal which is ready.
Sorry again for the direct email, but the community interaction links aren't active it seems.

**Comment by shamasis** [comment]
@adityaofficial10 I am closing this PR and instead will favour the project approach.

The end objective is to be able to take any curl command and replace `curl` with `Newman request` and have it work. Since it's a relatively large project with planning needed and it conflicts with this PR. There's no point going this way.

**Comment by adityaofficial10** [comment]
@shamasis 
I have sent you an email having a detailed account of this project.
Kindly check it.
I think that's the only way I can have a valuable review on that.🙏

**Comment by shamasis** [comment]
Have a look at this - https://github.com/postmanlabs/newman/pull/2657

This seems to have already gone forward very much in the right direction. Perhaps you can collaborate there?

**Comment by adityaofficial10** [comment]
@shamasis 
I'm also working on the parallel iterations concept along with this.
I have analyzed both the ideas and since they were in the issue tracker for a long time, I had been working on them for a month.
They can be combined in a single project.
Kindly review my proposal. 
That would help me a lot.

**Comment by shamasis** [comment]
Talk to Postman's GSOC team about this. I'm not handling that. But everyone here is always open to provide others with feedback and directions.

Parallel iterations seems like an interesting and challenging feature. Since a good part of it needs to be built inside runtime and not necessarily in newman, it would be interesting to see your approach. Handling linear CLI output for parallel iterations is another challenge. Dealing with shared resources such as environment and globals during parallel runs is another challenge.

Best wishes. These may require heavy planning. And we always recommend clearing out doubts with the Postman GSOC programme managers before you invest too much time into things.

**Comment by adityaofficial10** [comment]
@shamasis 
Can you guide me regarding the same because there's been absolutely no reply from the GSoC team?

**Comment by adityaofficial10** [comment]
I am thinking of multithreading and dividing the iteration data into multiple chunks and providing it to the threads which share the same environment and globals..
Once a thread gets free after an iteration, it gets allotted a new iteration. 
Threads communicate with each other using messages. 
Once the no. of running threads become 0, we claim that the run is complete.

**Comment by adityaofficial10** [comment]
Also, I have implemented something similar for 3 threads using worker_threads.

**Pull request closed without merging**
