### PR TITLE
Bumped runtime to v6.1.7-beta.8

### PR DESCRIPTION
**Pull request by kunagpal**

### CODE REVIEW

**Comment by czardoz** [comment]
Wait what. Why is this merged?

**Comment by kunagpal** [comment]
Doesn't this need to go in for the 3.7.0-beta.2 release?

**Comment by czardoz** [comment]
So why merge to develop?

**Comment by kunagpal** [comment]
The beta release can go out from develop, which avoids confusion if there are multiple betas from feature branches.

**Pull request merged**
