### PR TITLE
Add proxy support

### PR DESCRIPTION
**Pull request by jerryzhaoau**

### CODE REVIEW

**Comment by czardoz** [comment]
Thanks! I don't actually want to add another option for setting proxies though. Currently, they can be set using the standard environment variables, `HTTP_PROXY=<url>` etc. 

That ensures that Newman picks up the proxy from the system settings. Is there any other use case for which you need this to be a command line option?

**Comment by jerryzhaoau** [comment]
It would be more flexible when integrating with other systems in build pipelines. For example, it can be integrated to zaproxy to do a security scan for APIs.
Sometimes it may not possible to change system proxy in build server.

**Comment by shamasis** [comment]
@jerryzhaoau this should go in newman v3.1+ (not coded in newman but in postman-runtime so that even native apps can have a way to configure this)

**Comment by czardoz** [comment]
Closing this because it will be implemented in v3.1 :smile:

**Pull request closed without merging**
