### PR TITLE
docs(reporters): Add allure reporter to readme

### PR DESCRIPTION
**Pull request by vovsemenv**
Recently Allure created official newman reporter with support all of amazing features of newman. Let's add it to the readme 🚀

### CODE REVIEW

**Comment by vovsemenv** [comment]
@codenirvana 🤓

**Comment by vovsemenv** [comment]
guys?

**Review by codenirvana — APPROVED** [review]

**Comment by donatocayurin** [comment]
❤️🙏

**Comment by donatocayurin** [comment]
Thank you ❤️🙏

>

**Pull request merged**
