### PR TITLE
Feature/multiple collection run mentioned in issue #2117

### LINKED ISSUE #2117: Feature request: run with multiple files
Hello,
the `run` command could accept as input a regexp or a list of file in order to execute all the collection as a single one.

_Use case_

If you have a huge test suite you need to break up into multiple files.
Right now I have 140k request in 14 `.postman_collection` files.

You could use:

`for fn in `ls *.postman_collection`; do newman run $fn --env-var 'baseUrl=http://localhost:3000'; done`

But the bail logic is gone and I need bash scripting to manage the exit code and reports.

WDYT?

### PR DESCRIPTION
**Pull request by shubhamjadon**
Fixes #2117 
It implements feature requested in issue #2117 . After merging following changes developers will be able to run multiple collections as single one by just passing list of collection objects in Newman library.
Like this:
```
newman.run({
    collection: [require('./test1.json'),require('./test.json'),require('./test2.json')],
    reporters: 'cli',
    iterationCount: 2,

}, function (err) {
	if (err) { throw err; }
    console.log('collection run complete!');
});
```

### CODE REVIEW

**Comment by shubhamjadon** [comment]
@codenirvana, sure i will start working on some other approach to solve this issue.

And i thought of merging all the collections into one because of the following reasons:

- As in the issue #2262 , the user also wanted to run multiple collection together but he also needed the ability to access environment variables of one collection in other for the the purpose of authentication . So, to make that functionality available i thought it would be better to merge all collections into a single one.
- As you mentioned that this approach will be very confusing, to make it less confusing i made sure that all the collections are represented like separate folders inside the new collection created. So, user can make sense of which request belongs to which collection.
- And as you mentioned that such an interface can break a lot of existing reporters. So, i think it should not break any reporters as i am overwriting the options.collection with a combined collection in the very starting of the code so that it does not affects the later code and later code considers combined collection as the input collection.

Kindly share your review on following.

**Comment by shubhamjadon** [comment]
@codenirvana As suggested by you I found a new approach to solve issue #2117 it is as follows:
```
const newman = require('newman');
let collections = ['./test.json','./mycollection.postman_collection.json'];

(function runCollection(i = 0) {
    newman.run({
        collection: collections[i],
        reporters: 'cli',
        iterationCount: 1,
    }, function (err) {
        if(err){ throw err; }
        i++;
        if(i<collections.length){
            runCollection(i);
        }
        else{
            console.log("All Collections Run Complete!")
        }
    });
})();
```
This code is suitable for both single collection and multiple collections run. So, we can update the readme according to above.
PTAL and notify me , I will start pull request with the updated ReadMe.

**Comment by cupcakepanda89** [comment]
@shubhamjadon

Do you know if it is possible to pass the url-with-collection-id to this line `collection: collections[i]` ?

So I don't have to export the JSON files everytime there are changes.

**Comment by shubhamjadon** [comment]
@cupcakepanda89 
you can give a string of the URL where the Collection JSON can be found or path to a local JSON file.

**Comment by abhisheksingh999** [comment]
Hello @shubhamjadon thank for this. It is helpful. 
how do I run the above JavaScript from Windows command prompt?

**Comment by abhisheksingh999** [comment]
I get this error when i run npm run myLibrary.js
image

**Comment by abhisheksingh999** [comment]
@shubhamjadon How can I disable SSL, while running these collections. I used to use --insecure running single collection.

**Comment by shamasis** [comment]
Closing since the PR has the README change as well as code change. 

From what I can read at a glance, the original approach to merge collections isn't an advisable solution. The alternate is to provide simple example in wiki to have a script to use Newman programmatically. 

PS - A lot of core assumptions have to change to make Newman run multiple collections by itself. As such, that doesn't seem something that will be built in reasonable future.

**Comment by vijayarondla-mosaic** [comment]
@shubhamjadon  HI I was wondering how can we pass the Environment json file as an input . I am able to pass collections as url but i need to pass env also .If i give at the end of the collection string, it errors out . Thanks

**Comment by vijayarondla-mosaic** [comment]
I think i saw the documention let me try

**Pull request closed without merging**
